name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://blog.samarthya.me/wps/feed"
          max_post_count: 5
          template: "- **[$title]($url)** - *$date* $newline *$description*"
          date_format: "mmmm d, yyyy"
          description_max_length: 100
          tag_post_pre_newline: true
          filter_comments: true
          disable_sort: false
          categories_template: "[$category]"
          retry_count: 3
          enable_keepalive: true